name: rigify
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+27

environment:
  sdk: '>=3.2.0-134.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.9
  connectivity_plus: ^2.3.0
  http: ^0.13.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  font_awesome_flutter: ^10.4.0
  #app icon
  flutter_launcher_icons: ^0.11.0
  device_preview: ^1.1.0 #for debug
  device_preview_screenshot:
  change_app_package_name: ^1.1.0
  expandable: ^5.0.1

  jiffy: ^5.0.0
  pull_to_refresh: ^2.0.0
  timelines: ^0.1.0
  hive: ^2.2.3
  convex_bottom_bar: ^3.1.0+1
  flutter_svg: ^2.0.4
  flutter_native_splash: ^2.2.15
  animated_custom_dropdown: ^1.2.2
  google_mobile_ads: ^3.1.0
  url_launcher: ^6.2.1
  hooks_riverpod: ^2.4.5
  logging: ^1.2.0
  in_app_purchase: ^3.1.11

  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  firebase_core_platform_interface: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter_icons: #flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "assets/icon/icon_background.png"

flutter_native_splash: #flutter pub run flutter_native_splash:create
  color: "#2b343a"
  image: assets/splash/splash_icon.png

  android_12:
    image: assets/splash/splash_icon.png

flutter:

  assets:
    - assets/
    - assets/app_assets/
    - assets/certificates/

  uses-material-design: true

  generate: true


